export const GET_DOGS_REQUEST = "GET_DOGS_REQUEST"
export const GET_DOGS_SUCCESS = "GET_DOGS_SUCCESS"
export const GET_DOGS_FAIL = "GET_DOGS_FAIL" 
export const SET_CARRESEL_RANGE ="SET_CARRESEL_RANGE"
